package frc.robot.subsystems;

import edu.wpi.first.apriltag.AprilTagFieldLayout;
import edu.wpi.first.apriltag.AprilTagFields;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation3d;
import edu.wpi.first.math.geometry.Transform3d;
import edu.wpi.first.math.geometry.Translation3d;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.util.Units;

//Imports for Network Tables Functions
import edu.wpi.first.networktables.BooleanArrayPublisher;
import edu.wpi.first.networktables.BooleanPublisher;
import edu.wpi.first.networktables.DoubleArrayPublisher;
import edu.wpi.first.networktables.DoublePublisher;
import edu.wpi.first.networktables.IntegerArrayPublisher;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;

//Imports for photonVision Functions
import org.photonvision.PhotonCamera;
import org.photonvision.PhotonUtils;
import org.photonvision.targeting.PhotonPipelineResult;
import org.photonvision.targeting.PhotonTrackedTarget;
import org.photonvision.PhotonPoseEstimator;

import java.util.Arrays;
import java.util.List;
import java.util.Optional;

import org.photonvision.EstimatedRobotPose;

import edu.wpi.first.math.MatBuilder;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.Nat;
import edu.wpi.first.math.VecBuilder;

import frc.robot.subsystems.CommandSwerveDrivetrain;

public class precisionVision {

    private PhotonCamera turretCamera;
    private PhotonCamera leftRearCamera;
    private PhotonCamera rightRearCamera;
    private PhotonCamera leftFrontCamera;
    private PhotonCamera rightFrontCamera;

    private NetworkTable visionTurretData;
    private BooleanPublisher isOurGoalDetectedDisplay;
    private BooleanPublisher turretGoodLockDisplay;
    private DoubleArrayPublisher turretAnglesToGoalDisplay;
    private DoubleArrayPublisher turretDistancesToGoalDisplay;

    private DoublePublisher turretAngleToGoalAvgDisplay;
    private DoublePublisher turretDistanceToGoalAvgDisplay;
    private DoubleArrayPublisher turretXGoalDisplay;
    private double[] turretXGoal;
    private DoubleArrayPublisher turretYGoalDisplay;
    private double[] turretYGoal;
    private DoubleArrayPublisher turretPoseDisplay;

    public boolean turretGoodLock;
    private double[] turretAnglesToGoal;
    private double[] turretDistancesTogoal;

    public double turretAngleToGoal;
    public double turretDistanceTogoal;

    private NetworkTable visionLocalizationData;
    private DoubleArrayPublisher fieldLocX;
    private DoubleArrayPublisher fieldLocY;
    private DoubleArrayPublisher fieldLocRot;
    private Field2d field2DDisplay;

    private NetworkTable aprilTagList;
    private BooleanPublisher[] isTagDetectedDisplay;
    private final static int MAX_TAGS = 32;

    CommandSwerveDrivetrain thisCommandSwerveDrivetrain;
    // These are the Network tables for the cam data generated by each camera
    // private NetworkTable turretCamData;
    // private NetworkTable leftRearCamData;
    // private NetworkTable rightrearCamData;

    public static final AprilTagFieldLayout kTagLayout = AprilTagFieldLayout
            .loadField(AprilTagFields.k2026RebuiltAndymark);

    // Rotations for camera transformations need to be input as quaternions.
    // Use the Euler Angle to quaternion calculator:
    // https://articulatedrobotics.xyz/tools/rotation-calculator/
    // We prefer to do the ZYX Euler
    // These assume a Z(Yaw) of 45, 135, 225,315
    // These assume a Y(pitch) of -25
    // From that calculator we are using the Axis-Angle in radians

    public static final Transform3d kSledToFrontLeftCam = new Transform3d(new Translation3d(0.0508, 0.254, 0.52),
            new Rotation3d(Units.degreesToRadians(0), Units.degreesToRadians(-25), Units.degreesToRadians(45)));

    public static final Transform3d kSledToLeftRearCam = new Transform3d(new Translation3d(-0.0508, 0.254, 0.52),
            new Rotation3d(Units.degreesToRadians(0), Units.degreesToRadians(-25), Units.degreesToRadians(135)));

    public static final Transform3d kSledToRightRearCam = new Transform3d(new Translation3d(-0.0508, -0.254, 0.52),
            new Rotation3d(Units.degreesToRadians(0), Units.degreesToRadians(-25), Units.degreesToRadians(-135)));

    public static final Transform3d kSledToFrontRightCam = new Transform3d(new Translation3d(0.0508, -0.254, 0.52),
            new Rotation3d(Units.degreesToRadians(0), Units.degreesToRadians(-25), Units.degreesToRadians(-45)));

    public static final Transform3d kSledToTurret = new Transform3d(new Translation3d(0, 0, 0.203),
            new Rotation3d(0, -0.436, 0)); // Turret is in camera coordinate system and no transformation is applied.
    public boolean isOurGoalDetected;
    private boolean weAreBlueAlliance;

    private PhotonPoseEstimator turretPoseEstimator;
    private PhotonPoseEstimator leftRearPoseEstimator;
    private PhotonPoseEstimator rightRearPoseEstimator;
    private PhotonPoseEstimator leftFrontPoseEstimator;
    private PhotonPoseEstimator rightFrontPoseEstimator;

    private cameraContainer frLeftContainer;
    private cameraContainer BaLeftContainer;
    private cameraContainer FrRightContainer;
    private cameraContainer BaRightContainer;

    class cameraContainer {
        PhotonCamera thisCamera;
        PhotonPoseEstimator thisPoseEstimator;
        int arrayIndex;
    };

    // parameters for tracking status of april tag detection
    boolean[] isTagDetected;
    List<cameraContainer> chassisCameras;
    double[] visionXest;
    double[] VisionYest;
    double[] VisionRest;

    public precisionVision() {
        // This is the default constructor

        // Initialize the visionnetwork tables
        visionTurretData = NetworkTableInstance.getDefault().getTable("VisionTurretData");
        isOurGoalDetectedDisplay = visionTurretData.getBooleanTopic("Is OUR  Goal Detected?").publish();
        turretGoodLockDisplay = visionTurretData.getBooleanTopic("LOCKED ON TO GOAL").publish();
        turretAngleToGoalAvgDisplay = visionTurretData.getDoubleTopic("ANGLE TO Goal").publish();
        turretDistanceToGoalAvgDisplay = visionTurretData.getDoubleTopic("DISTANCE To Goal").publish();
        turretAnglesToGoalDisplay = visionTurretData.getDoubleArrayTopic("ANGLEs TO Goal").publish();
        turretDistancesToGoalDisplay = visionTurretData.getDoubleArrayTopic("DISTANCEsTo Goal").publish();
        turretXGoalDisplay = visionTurretData.getDoubleArrayTopic("xTrans To Goal").publish();
        turretYGoalDisplay = visionTurretData.getDoubleArrayTopic("yTrans To Goal").publish();
        turretXGoal = new double[3];
        turretYGoal = new double[3];
        turretPoseDisplay = visionTurretData.getDoubleArrayTopic("TurretPoseEstimate").publish();

        // locatlization Tables
        visionLocalizationData = NetworkTableInstance.getDefault().getTable("LocalizationData");
        fieldLocX = visionLocalizationData.getDoubleArrayTopic("fieldLocX").publish();
        fieldLocY = visionLocalizationData.getDoubleArrayTopic("fieldLocY").publish();
        fieldLocRot = visionLocalizationData.getDoubleArrayTopic("fieldLocRot").publish();
        // field2DDisplay = new Field2d("2026Field");

        aprilTagList = NetworkTableInstance.getDefault().getTable("AprilTagList");

        isTagDetectedDisplay = new BooleanPublisher[MAX_TAGS];
        for (int i = 0; i < MAX_TAGS; i++) {
            String tagPublisherName = "Tag" + String.format("%02d", i + 1) + "isSeen";
            isTagDetectedDisplay[i] = aprilTagList.getBooleanTopic(tagPublisherName).publish();
        }

        turretAnglesToGoal = new double[3];
        turretDistancesTogoal = new double[3];

        // createContainers for Analyzing Tags
        isTagDetected = new boolean[MAX_TAGS];

        // Connect to the cameras
        turretCamera = new PhotonCamera("TurretCamera");
        leftRearCamera = new PhotonCamera("LeftRearCamera");
        rightRearCamera = new PhotonCamera("RightRearCamera");
        leftFrontCamera = new PhotonCamera("LeftFrontCamera");
        rightFrontCamera = new PhotonCamera("RightFrontCamera");

        // Construct things for localization
        turretPoseEstimator = new PhotonPoseEstimator(kTagLayout, kSledToTurret);
        leftRearPoseEstimator = new PhotonPoseEstimator(kTagLayout, kSledToLeftRearCam);
        rightRearPoseEstimator = new PhotonPoseEstimator(kTagLayout, kSledToRightRearCam);
        leftFrontPoseEstimator = new PhotonPoseEstimator(kTagLayout, kSledToFrontLeftCam);
        rightFrontPoseEstimator = new PhotonPoseEstimator(kTagLayout, kSledToFrontRightCam);

        // private Matrix<N3, N1> curStdDevs;

        // Temporary Container for chassisCameras
        frLeftContainer = new cameraContainer();
        frLeftContainer.thisCamera = leftFrontCamera;
        frLeftContainer.thisPoseEstimator = leftFrontPoseEstimator;
        frLeftContainer.arrayIndex = 0;
        // chassisCameras.add(frLeftContainer);

        BaLeftContainer = new cameraContainer();
        BaLeftContainer.thisCamera = leftRearCamera;
        BaLeftContainer.thisPoseEstimator = leftRearPoseEstimator;
        BaLeftContainer.arrayIndex = 1;
        // chassisCameras.add(BaLeftContainer);

        BaRightContainer = new cameraContainer();
        BaRightContainer.thisCamera = rightRearCamera;
        BaRightContainer.thisPoseEstimator = rightRearPoseEstimator;
        BaRightContainer.arrayIndex = 2;
        // chassisCameras.add(BaRightContainer);

        FrRightContainer = new cameraContainer();
        FrRightContainer.thisCamera = rightFrontCamera;
        FrRightContainer.thisPoseEstimator = rightFrontPoseEstimator;
        FrRightContainer.arrayIndex = 3;
        // chassisCameras.add(FrRightContainer);

        chassisCameras = Arrays.asList(
                frLeftContainer,
                BaLeftContainer,
                BaRightContainer,
                FrRightContainer);

        visionXest = new double[5];
        VisionYest = new double[5];
        VisionRest = new double[5];

    }

    public void attachDriveTrain(CommandSwerveDrivetrain aDrivetrainCommandSwerveDrivetrain) {
        thisCommandSwerveDrivetrain = aDrivetrainCommandSwerveDrivetrain;

        return;
    }

    public boolean periodicUpdate() {
        // Call this periodically to service cameras and update position estimates
        try {
            /// ************ THIS SECTION DEALS WITH THE TURRET ONLY ******************** /
            // Initialize all tags to fase so that as we iterate through tags we can check
            /// which ones are true
            for (int i = 0; i < MAX_TAGS; i++) {
                isTagDetected[i] = false;
            }
            turretGoodLock = false;

            // determine check all of the tags
            var turretCAMResults = turretCamera.getAllUnreadResults();
            if (!turretCAMResults.isEmpty()) {
                var aTurretCAMResult = turretCAMResults.get(turretCAMResults.size() - 1);
                if (aTurretCAMResult.hasTargets()) {
                    // At least one AprilTag was seen by the camera
                    for (var target : aTurretCAMResult.getTargets()) {
                        isTagDetected[target.getFiducialId() - 1] = true;
                        calculateGoalLocationFromTag(target);
                        calculateGoalLocationFromTurretPose(target);

                    } // End of iterating over targets

                } // End of check for has targets

            } // End of check for has results

            turretXGoalDisplay.set(turretXGoal);
            turretYGoalDisplay.set(turretYGoal);

            double[] anglesInDegs = { turretAnglesToGoal[0] * 180 / 3.14, turretAnglesToGoal[1] * 180 / 3.14,
                    turretAnglesToGoal[2] * 180 / 3.14 };
            turretAnglesToGoalDisplay.set(anglesInDegs);
            turretDistancesToGoalDisplay.set(turretDistancesTogoal);

            // Print all of the tag statuses to network tables to be used by elastic
            for (int i = 0; i < MAX_TAGS; i++) {
                isTagDetectedDisplay[i].set(isTagDetected[i]);
            }

            // determine if ourGoalWasDetected
            int[] ourGoalTagList;
            int[] redGoalTagList = { 5, 10, 2 };
            int[] blueGoalTagList = { 21, 26, 18 };
            if (weAreBlueAlliance) {
                ourGoalTagList = blueGoalTagList;
            } else {
                ourGoalTagList = redGoalTagList;
            }
            boolean tempOurGoalDetected = false;
            for (int i = 0; i < 3; i++) {
                tempOurGoalDetected = tempOurGoalDetected || checkTagDetected(ourGoalTagList[i]);
            }
            isOurGoalDetected = tempOurGoalDetected;
            isOurGoalDetectedDisplay.set(isOurGoalDetected);
            turretGoodLockDisplay.set(turretGoodLock);

            // TODO: This method for calculating averages sucks and should be fixed
            double avgAngle = 0;
            double avgDist = 0;
            double goalTgtsSeen = 0;

            for (int i = 0; i < 3; i++) {
                if (checkTagDetected(ourGoalTagList[i])) {
                    avgAngle = avgAngle + turretAnglesToGoal[i];
                    avgDist = avgDist + turretDistancesTogoal[i];
                    goalTgtsSeen++;
                }

            }
            avgAngle = avgAngle / goalTgtsSeen;
            avgDist = avgDist / goalTgtsSeen;

            turretAngleToGoalAvgDisplay.set(avgAngle);
            turretDistanceToGoalAvgDisplay.set(avgDist);

            turretDistanceTogoal = avgDist;
            turretAngleToGoal = avgAngle;
        } catch (Exception e) {

        }
        // ************** THIS SECTION DEALS WITH LOCALIZATION ESTIMATES * /

        for (cameraContainer aCameraContainer : chassisCameras) {

            Optional<EstimatedRobotPose> visionEst = Optional.empty();

            // cameraContainer aCameraContainer = BaRightContainer;

            for (var result : aCameraContainer.thisCamera.getAllUnreadResults()) {
                visionEst = aCameraContainer.thisPoseEstimator.estimateCoprocMultiTagPose(result);
                if (visionEst.isEmpty()) {
                    visionEst = aCameraContainer.thisPoseEstimator.estimateLowestAmbiguityPose(result); // default to 2d
                                                                                                        // localization
                                                                                                        // if we can't
                                                                                                        // get multi-tag
                                                                                                        // results

                }
                // updateEstimationStdDevs(visionEst, result.getTargets());
                if (!visionEst.isEmpty()) {
                    visionXest[aCameraContainer.arrayIndex] = visionEst.get().estimatedPose.getX();
                    VisionYest[aCameraContainer.arrayIndex] = visionEst.get().estimatedPose.getY();
                    VisionRest[aCameraContainer.arrayIndex] = visionEst.get().estimatedPose.getRotation().getZ() * 180
                            / 3.14;

                    thisCommandSwerveDrivetrain.addVisionMeasurement(visionEst.get().estimatedPose.toPose2d(),
                            visionEst.get().timestampSeconds);

                }

            }

        }

        visionXest[4] = thisCommandSwerveDrivetrain.samplePoseAt(Timer.getFPGATimestamp()).get().getX();
        VisionYest[4] = thisCommandSwerveDrivetrain.samplePoseAt(Timer.getFPGATimestamp()).get().getY();
        VisionRest[4] = thisCommandSwerveDrivetrain.samplePoseAt(Timer.getFPGATimestamp()).get().getRotation()
                .getDegrees();

        fieldLocX.set(visionXest);
        fieldLocY.set(VisionYest);
        fieldLocRot.set(VisionRest);

        return true;
    }

    /********* External Functions */

    public void setWeAreBlueAliance(boolean areWeBlueAlliance) {
        weAreBlueAlliance = areWeBlueAlliance;
    }

    ///// ******** Turret Getters ********/
    public double getTurretAngleToGoalDeg() {
        return turretAngleToGoal * 180 / 3.14159;

    }

    public double getTurretAngleToGoalRad() {

        return turretAngleToGoal;

    }

    public double getTurretDistanceToGoalMeters() {
        // Returns distance to target in radians
        return turretDistanceTogoal;
    }

    public double getTurretDistanceToGoalInches() {
        return turretDistanceTogoal * 39.3701;

    }

    @FunctionalInterface
    public static interface EstimateConsumer {
        public void accept(Pose2d pose, double timestamp, Matrix<N3, N1> estimationStdDevs);
    }

    /********* Internal Helper Functions *******/
    private boolean checkTagDetected(int tag) {
        return isTagDetected[tag - 1];

    }

    class turretSolution {
        double distance;
        double angle;
        boolean IsValid;

        turretSolution() {
            distance = 0;
            angle = 0;
            IsValid = false;

        }
    }
    class chassisSolution{
        double distance;
        double angle;

        chassisSolution(){
            distance = 0;
            angle = 0;
        }
    }

    private turretSolution calculateGoalLocationFromTag(PhotonTrackedTarget target) {
        // This method will return the distance (in M) and angle (in Rad) to the target
        // if it sees one of the "goal-center" April Tags
        // It Takes a "target"
        // It returns [distance,angleToTarget]

        int[] redGoalTagList = { 5, 10, 2 };
        int[] blueGoalTagList = { 21, 26, 18 };
        boolean thisTargetIsAGoal = false;

        // Initialize something to return
        turretSolution aTurretSolution = new turretSolution();

        int targetID = target.getFiducialId();
        int displayIndex = 0; // The index of the diplay vector 0 for left, 1 for center, 2 for right;

        if (target.poseAmbiguity > 0.2) { // If the pose ambiguity is bad, throw out the value and return an invalid
                                          // solutoin (high ambiguiity is bad)
            aTurretSolution.IsValid = false;
            return aTurretSolution;
        }

        if (weAreBlueAlliance) {
            // if we are the blue alliance alliance, calculate the goal location from the
            // target data
            if (targetID == 21 || targetID == 26 || targetID == 18) { // Check to make sure that the targetID is one of
                                                                      // the blue goal targets
                turretGoodLock = true;
                thisTargetIsAGoal = true;
                switch (targetID) {
                    case 21:
                        displayIndex = 0;
                        break;

                    case 26:
                        displayIndex = 1;
                        break;
                    case 18:
                        displayIndex = 2;
                        break;

                    default:

                }
            }

        } else {
            // If we are the red alliance
            if (targetID == 5 || targetID == 10 || targetID == 2) { // Check to make sure that the TargetID id one of
                                                                    // the red goal targets
                turretGoodLock = true;
                thisTargetIsAGoal = true;
                switch (targetID) {
                    case 5:
                        displayIndex = 0;
                        break;

                    case 10:
                        displayIndex = 1;
                        break;
                    case 2:
                        displayIndex = 2;
                        break;

                    default:

                }

            }

            if (thisTargetIsAGoal) {
                double x = target.getBestCameraToTarget().getX();
                double y = target.getBestCameraToTarget().getY();
                double z = target.getBestCameraToTarget().getRotation().getZ() + 3.141593;

                double alpha = Math.atan(y / x);
                double d = Math.sqrt(x * x + y * y);

                double beta = z - alpha;

                double Xg = d * Math.cos(alpha) + 0.5931 * Math.cos(alpha + beta);
                double Yg = d * Math.sin(alpha) + 0.5931 * Math.sin(alpha + beta);

                double thetaG = Math.atan(Yg / Xg);
                double distG = Math.sqrt(Xg * Xg + Yg * Yg);

                turretDistancesTogoal[displayIndex] = distG;
                turretAnglesToGoal[displayIndex] = thetaG;

                turretXGoal[displayIndex] = Xg;
                turretYGoal[displayIndex] = Yg;

                aTurretSolution.IsValid = true;
                aTurretSolution.angle = thetaG;
                aTurretSolution.distance = distG;

            }

        }

        return aTurretSolution;

    }

    private double[] blueGoalLocation = { 4.611, 4.021 }; // (x,y) blueGoal is at (181.56,158.32) inches
    private double[] redGoalLocation = { 11.901, 4.021 }; // (x,y)redGoal is at (468.56,158.32) inches

    private turretSolution calculateGoalLocationFromTurretPose(PhotonTrackedTarget target) {
        turretSolution aTurretSolution = new turretSolution();
        double turretLocX = 0;
        double turretLocY = 0;
        double turretLocRot = 0;

        double[] ourGoalLocation;

        Optional<EstimatedRobotPose> thisVisionEst = Optional.empty();
        for (var result : turretCamera.getAllUnreadResults()) {
            thisVisionEst = turretPoseEstimator.estimateCoprocMultiTagPose(result);
            if (thisVisionEst.isEmpty()) {
                thisVisionEst = turretPoseEstimator.estimateLowestAmbiguityPose(result); // default to 2d localization
                                                                                         // if we can't get multi-tag
                                                                                         // results

            }

            turretLocX = thisVisionEst.get().estimatedPose.getX();
            turretLocY = thisVisionEst.get().estimatedPose.getY();
            turretLocRot = thisVisionEst.get().estimatedPose.getRotation().getZ();

            if (weAreBlueAlliance)
                ourGoalLocation = blueGoalLocation;
            else
                ourGoalLocation = redGoalLocation;

            // calcualte the distance
            aTurretSolution.distance = Math
                    .sqrt(Math.pow(turretLocX - ourGoalLocation[0], 2) + Math.pow(turretLocY - ourGoalLocation[1], 2));

            // calculate the angle
            aTurretSolution.angle = Math.atan((ourGoalLocation[1] - turretLocY) / (ourGoalLocation[0] - turretLocX))
                    - turretLocRot;

            double[] solutiotDisplayVector = { aTurretSolution.distance, aTurretSolution.angle * 180 / 3.1416,
                    turretLocX, turretLocY, turretLocRot };
            turretPoseDisplay.set(solutiotDisplayVector);
        }

        return aTurretSolution;
    }

    private Matrix<N3, N1> curStdDevs;
    private Matrix<N3, N1> kSingleTagStdDevs;// TODO: Where are these supposed to come from?
    private Matrix<N3, N1> kMultiTagStdDevs; // TODO: Where are these supposed to come from?

    private void updateEstimationStdDevs(
            Optional<EstimatedRobotPose> estimatedPose, List<PhotonTrackedTarget> targets) {
        if (estimatedPose.isEmpty()) {
            // No pose input. Default to single-tag std devs
            curStdDevs = kSingleTagStdDevs;

        } else {
            // Pose present. Start running Heuristic
            var estStdDevs = kSingleTagStdDevs;
            int numTags = 0;
            double avgDist = 0;

            // Precalculation - see how many tags we found, and calculate an
            // average-distance metric
            for (var tgt : targets) {
                var tagPose = leftRearPoseEstimator.getFieldTags().getTagPose(tgt.getFiducialId());
                if (tagPose.isEmpty())
                    continue;
                numTags++;
                avgDist += tagPose
                        .get()
                        .toPose2d()
                        .getTranslation()
                        .getDistance(estimatedPose.get().estimatedPose.toPose2d().getTranslation());
            }

            if (numTags == 0) {
                // No tags visible. Default to single-tag std devs
                curStdDevs = kSingleTagStdDevs;
            } else {
                // One or more tags visible, run the full heuristic.
                avgDist /= numTags;
                // Decrease std devs if multiple targets are visible
                if (numTags > 1)
                    estStdDevs = kMultiTagStdDevs;
                // Increase std devs based on (average) distance
                if (numTags == 1 && avgDist > 4)
                    estStdDevs = VecBuilder.fill(Double.MAX_VALUE, Double.MAX_VALUE, Double.MAX_VALUE);
                else
                    estStdDevs = estStdDevs.times(1 + (avgDist * avgDist / 30));
                curStdDevs = estStdDevs;
            }
        }
    }



    public chassisSolution estimateGoalLocationFromChassis(){
       
        double chassisLocX=0;
        double chassisLocY=0;
        double chassisLocRot=0;

        chassisSolution aChassisSolution = new chassisSolution();

        double [] ourGoalLocation;

      
                if(weAreBlueAlliance) ourGoalLocation = blueGoalLocation;
                else ourGoalLocation = redGoalLocation;
                
                chassisLocX = thisCommandSwerveDrivetrain.samplePoseAt(Timer.getFPGATimestamp()).get().getX();
                chassisLocY =  thisCommandSwerveDrivetrain.samplePoseAt(Timer.getFPGATimestamp()).get().getY();
                chassisLocRot = thisCommandSwerveDrivetrain.samplePoseAt(Timer.getFPGATimestamp()).get().getRotation().getRadians();

                //calcualte the distance
                aChassisSolution.distance = Math.sqrt( Math.pow(chassisLocX - ourGoalLocation[0],2) + Math.pow(chassisLocX - ourGoalLocation[1],2));

                //calculate the angle
                aChassisSolution.angle = Math.atan((ourGoalLocation[1]-chassisLocY) / (ourGoalLocation[0]-chassisLocX)) - chassisLocRot;
        
           return aChassisSolution;

        }

    public double estimateGoalRotationFromChassis(){
       
        double chassisLocX=0;
        double chassisLocY=0;
        double chassisLocRot=0;

        chassisSolution aChassisSolution = new chassisSolution();

        double [] ourGoalLocation;

      
                if(weAreBlueAlliance) ourGoalLocation = blueGoalLocation;
                else ourGoalLocation = redGoalLocation;
                
                chassisLocX = thisCommandSwerveDrivetrain.samplePoseAt(Timer.getFPGATimestamp()).get().getX();
                chassisLocY =  thisCommandSwerveDrivetrain.samplePoseAt(Timer.getFPGATimestamp()).get().getY();
                chassisLocRot = thisCommandSwerveDrivetrain.samplePoseAt(Timer.getFPGATimestamp()).get().getRotation().getRadians();

                //calcualte the distance
                aChassisSolution.distance = Math.sqrt( Math.pow(chassisLocX - ourGoalLocation[0],2) + Math.pow(chassisLocY - ourGoalLocation[1],2));

                //calculate the angle
                aChassisSolution.angle = Math.atan((ourGoalLocation[1]-chassisLocY) / (ourGoalLocation[0]-chassisLocX)) - chassisLocRot;
        
           return aChassisSolution.angle;

        }

    public double estimateGoalDistanceFromChassis(){
       
        double chassisLocX=0;
        double chassisLocY=0;
        double chassisLocRot=0;

        chassisSolution aChassisSolution = new chassisSolution();

        double [] ourGoalLocation;

      
                if(weAreBlueAlliance) ourGoalLocation = blueGoalLocation;
                else ourGoalLocation = redGoalLocation;
                
                chassisLocX = thisCommandSwerveDrivetrain.samplePoseAt(Timer.getFPGATimestamp()).get().getX();
                chassisLocY =  thisCommandSwerveDrivetrain.samplePoseAt(Timer.getFPGATimestamp()).get().getY();
                chassisLocRot = thisCommandSwerveDrivetrain.samplePoseAt(Timer.getFPGATimestamp()).get().getRotation().getRadians();

                //calcualte the distance
                aChassisSolution.distance = Math.sqrt( Math.pow(chassisLocX - ourGoalLocation[0],2) + Math.pow(chassisLocX - ourGoalLocation[1],2));

                //calculate the angle
                aChassisSolution.angle = Math.atan((ourGoalLocation[1]-chassisLocY) / (ourGoalLocation[0]-chassisLocX)) - chassisLocRot;
        
           return aChassisSolution.distance;

        }



       
    }





